### ISSUE TITLE
Suggestion for a few additions

### ISSUE THREAD

**Issue by cornelpv** [wujood/awesome-gamejam#10]
I suggest the following additions

For Pixel editor: [PiskelApp](https://www.piskelapp.com/) powerful and free pixel editor.

For frameworks:
- [LibGDX](https://libgdx.com/) Java based game framework;
- [Love2d](https://love2d.org/) Lua based framework.

**Comment by wujood** [comment]
Thanks for the suggestions! I have added them in https://github.com/wujood/awesome-gamejam/commit/697a7f444e3dcc7439a320f33862c22ad9a4bf16
